version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: soundcloud_clone
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/soundcloud_clone?autoReconnect=true&useSSL=false
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
volumes:
  mysql_data: