FROM openjdk:8-jdk-alpine
MAINTAINER nguyenquocquan.nbk.9a5@gmail.com
COPY target/soundcloud-clone-backend-1.0.0.jar soundcloud-clone-backend-1.0.0.jar
ENTRYPOINT ["java","-jar","/message-server-1.0.0.jar"]