server:
  error:
    include-message: always
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/soundcloud_clone
    username: quan
    password: Vamario256
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 224832482994-s83lolfpg135t42kjrm57j9mq9fqk1ho.apps.googleusercontent.com
            client-secret: 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
          facebook:
            client-id: 1333281894211704
            client-secret: a832e441b28b99d7ee4101695d18f093
  main:
    allow-bean-definition-overriding: true

aws:
  region: ap-southeast-1
  s3:
    buckets:
      customer: vamirio-soundcloud-clone