GOOGLE_CLIENT_SECRECT: "224832482994-s83lolfpg135t42kjrm57j9mq9fqk1ho.apps.googleusercontent.com"
GOOGLE_CLIENT_ID: "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"

FACEBOOK_CLIENT_SECRECT: "1333281894211704"
FACEBOOK_CLIENT_ID: "a832e441b28b99d7ee4101695d18f093"

MYSQL_USERNAME: "quan"
MYSQL_PASSWORD: "Vamario256"
MYSQL_SCHEMA: "soundcloud_clone"

AWS_REGION: "ap-southeast-1"
AWS_BUCKET: "vamirio-soundcloud-clone"