export const data = [
  {
    images: require("../assets/images/Rectangle 217.png"),
    title: "Playlist 1",
    id: 1,
  },
  {
    images: require("../assets/images/Rectangle 246 (1).png"),
    title: "Playlist 2",
    id: 2,
  },
];
export const genre_data = [
  {
    title: "Podcast",
    color: "#27856A",
    link: require("../assets/genre/postcast.png"),
  },
  {
    title: "V-POP ",
    color: "#477D95",
    link: require("../assets/genre/image 5 (1).png"),
  },
  {
    title: "K-POP",
    color: "#148A08",
    link: require("../assets/genre/image 5 (2).png"),
  },
  {
    title: "US-UK",
    color: "#8C1932",
    link: require("../assets/genre/image 5 (3).png"),
  },
  {
    title: "Chill",
    color: "#BA5D07",
    link: require("../assets/genre/image 5 (4).png"),
  },
  {
    title: "Mood",
    color: "#509BF5",
    link: require("../assets/genre/image 5 (6).png"),
  },
  {
    title: "Romance",
    color: "#FF4632",
    link: require("../assets/genre/image 5 (7).png"),
  },
  {
    title: "Jazz",
    color: "#8D67AB",
    link: require("../assets/genre/image 5 (5).png"),
  },
];
export const songsdata = [
  {
    title: "Biên Vạn Thiên (别万千)",
    artist: "DAWN",
    url: require("../assets/music/Bien Van Thien - DAWN.mp3"),
    image: require("../assets/music/1.jpg"),
    duration: "3:25",
    currentTime: 0,
  },
  {
    title: "Pháo Hồng",
    artist: "Đạt Long Vinh",
    url: require("../assets/music/Phao Hong - Dat Long Vinh.m4a"),
    image: require("../assets/music/3.jpg"),
    duration: "3:55",
    currentTime: 0,
  },
  {
    title: "Bones",
    artist: "Image Dragon",
    url: require("../assets/music/Image Dragon.mp3"),
    image: require("../assets/music/2.jpg"),
    duration: "2:45",
    currentTime: 0,
  },
];
export const first_slide_home_data = [
  {
    image: require("../assets/images/temp_img.jpg"),
    title: "Born to die",
    description: "Lana Del ReY",
    newtype: 0,
    artist: "Lana Del ReY",
    url: require("../assets/music/Born To Die - Lana Del Rey.m4a"),
    duration: "4:46",
    currentTime: 0,
  },
  {
    image: require("../assets/home/Rectangle 189.png"),
    title: "DOCD Chill",
    description: "Playlist",
    newtype: 2,
  },
  {
    image: require("../assets/home/Rectangle 189 (1).png"),
    title: "South Of Heaven",
    description: "Slayer",
    newtype: 0,
    artist: "Slayer",
    url: require("../assets/music/South Of Heaven - Slayer.m4a"),
    duration: "4:58",
    currentTime: 0,
  },
  {
    image: require("../assets/home/Rectangle 189 (2).png"),
    title: "Queen",
    description: "Nghệ sĩ",
    newtype: 1,
  },
  {
    image: require("../assets/home/Rectangle 189 (3).png"),
    title: "99vande",
    description: "GG y u n k",
    newtype: 0,
  },
  {
    image: require("../assets/home/Rectangle 189 (4).png"),
    title: "Lạc",
    description: "Rhymastic",
    newtype: 0,
  },
  {
    image: require("../assets/home/Rectangle 189 (5).png"),
    title: "Rap Việt",
    description: "Karik, Binz",
    newtype: 2,
  },
  {
    image: require("../assets/home/Rectangle 189 (6).png"),
    title: "Mr.Siro Collection",
    description: "Mr.siro",
    newtype: 2,
  },
  {
    image: require("../assets/home/Rectangle 189 (7).png"),
    title: "EDM Việt",
    description: "K-ICM, Tuoliver",
    newtype: 0,
  },
];
export const second_slide_home_data = [
  {
    image: require("../assets/home/Rectangle 189 (8).png"),
    title: "New Light",
    description: "Eric Bellinger",
    newtype: 0,
    artist: "Eric Bellinger",
    url: require("../assets/music/New Light - John Mayer.m4a"),
    duration: "3:36",
    currentTime: 0,
  },
  {
    image: require("../assets/home/Rectangle 189 (9).png"),
    title: "Ziggly Mixtapes",
    description: "Haziq Hafiy",
    newtype: 0,
    artist: "Haziq Hafiy",
    url: require("../assets/music/New Light - John Mayer.m4a"),
    duration: "3:36",
    currentTime: 0,
  },
  {
    image: require("../assets/home/Rectangle 189 (10).png"),
    title: "Take a trip",
    description: "Postwood",
    newtype: 0,
    artist: "Postwood",
    url: require("../assets/music/True Love - NuNew.m4a"),
    duration: "3:36",
    currentTime: 0,
  },
  {
    image: require("../assets/home/Rectangle 189 (11).png"),
    title: "Happier Than Ever",
    description: "Billie Eilish",
    newtype: 2,
  },
  {
    image: require("../assets/home/Rectangle 189 (12).png"),
    title: "Say So",
    description: "Nicki Minaj",
    newtype: 0,
    artist: "Nicki Minaj",
    url: require("../assets/music/New Light - John Mayer.m4a"),
    duration: "3:36",
    currentTime: 0,
  },
  {
    image: require("../assets/home/Rectangle 189 (13).png"),
    title: "Cure For Me",
    description: "AURORA",
    newtype: 2,
  },
  {
    image: require("../assets/home/Rectangle 189 (14).png"),
    title: "Bohemian Rhap...",
    description: "Queen",
    newtype: 0,
    artist: "Queen",
    url: require("../assets/music/New Light - John Mayer.m4a"),
    duration: "3:36",
    currentTime: 0,
  },
  {
    image: require("../assets/home/Rectangle 189 (15).png"),
    title: "The Neighbourhood",
    description: "Nghệ sĩ",
    newtype: 1,
  },
  {
    image: require("../assets/home/Rectangle 189 (16).png"),
    title: "Lana Del Rey",
    description: "Nghệ sĩ",
    newtype: 1,
  },
];
export const third_slide_home_data = [
  {
    image: require("../assets/home/Rectangle 189 (17).png"),
    title: "Top 50 - Việt Nam",
    description: "",
    newtype: 0,
  },
  {
    image: require("../assets/home/Rectangle 189 (18).png"),
    title: "Top 50 - Toàn cầu",
    description: "",
    newtype: 0,
  },
];
export const like_data = {
  data_slide: [
    {
      image: require("../assets/images/temp_img.jpg"),
      title: "Born to die",
      description: "Lana Del ReY",
      newtype: 0,
      artist: "Lana Del ReY",
      url: require("../assets/music/Born To Die - Lana Del Rey.m4a"),
      duration: "4:46",
      currentTime: 0,
    },
    {
      image: require("../assets/home/Rectangle 189 (1).png"),
      title: "South Of Heaven",
      description: "Slayer",
      newtype: 0,
      artist: "Slayer",
      url: require("../assets/music/South Of Heaven - Slayer.m4a"),
      duration: "4:58",
      currentTime: 0,
    },
    {
      image: require("../assets/home/Rectangle 189 (3).png"),
      title: "99vande",
      description: "GG y u n k",
      newtype: 0,
    },
    {
      image: require("../assets/home/Rectangle 189 (4).png"),
      title: "Lạc",
      description: "Rhymastic",
      newtype: 0,
    },
    {
      image: require("../assets/home/Rectangle 189 (7).png"),
      title: "EDM Việt",
      description: "K-ICM, Tuoliver",
      newtype: 0,
    },
  ],
  title: "Bài hát đã thích",
  description: "19 bài hát · Cập nhật hôm qua",
  category_title: "Bài hát đã thích",
  category_count: "219 bài hát",
  category_content: `HEIZE You, <span>Cloud</span>, Rain · <span>NF The Search</span> · Tom Odell Another Love ·<span>Eden Circle</span> · Halsey Bad at love · <span>Radiohead Creep</span>...`,
  type: 1,
};
export const download = {
  data_slide: second_slide_home_data,
  title: "PlayList tải xuống",
  description: "6 playlist · Cập nhật hôm qua",
  category_title: "Bài hát tải xuống",
  category_count: "118 bài hát",
  category_content: `HEIZE You, <span>Cloud</span>, Rain · <span>NF The Search</span> · Tom Odell Another Love ·<span>Eden Circle</span> · Halsey Bad at love · <span>Radiohead Creep</span>...`,
  type: 1,
};

export const album = {
  data_slide: [
    {
      image: require("../assets/album/Rectangle 189 (26).png"),
      title: "Buồn của Rap Việt",
      description: "Đạt G, Dế Choắt",
      newtype: 2,
    },
    {
      image: require("../assets/album/Rectangle 189 (27).png"),
      title: "VPOP 2021",
      description: "Erik, Lyly",
      newtype: 2,
    },
    {
      image: require("../assets/album/Rectangle 189 (28).png"),
      title: "Rap Việt ngày nay",
      description: "MCK, tlinh ",
      newtype: 2,
    },
    {
      image: require("../assets/album/Rectangle 189 (29).png"),
      title: "Mr.Siro Collection",
      description: "Mr.siro",
      newtype: 2,
    },
    {
      image: require("../assets/album/Rectangle 189 (30).png"),
      title: "Isia tune",
      description: "Những bài hát Châu Á",
      newtype: 2,
    },
  ],
  title: "Album của bạn",
  description: "",
  category_title: "",
  category_count: "",
  category_content: ``,
  type: 0,
};
export const artist_data = {
  data_slide: [
    {
      image: require("../assets/album/Rectangle 189 (31).png"),
      title: "Đen Vâu",
      description: "Nghệ sĩ",
      newtype: 1,
    },
    {
      image: require("../assets/album/Rectangle 189 (32).png"),
      title: "Lana Del Rey",
      description: "Nghệ sĩ",
      newtype: 1,
    },
    {
      image: require("../assets/album/Rectangle 189 (33).png"),
      title: "The Neighbouhood",
      description: "Nghệ sĩ",
      newtype: 1,
    },
    {
      image: require("../assets/album/Rectangle 189 (34).png"),
      title: "Yonezu Kenshi",
      description: "Nghệ sĩ",
      newtype: 1,
    },
    {
      image: require("../assets/album/Rectangle 189 (35).png"),
      title: "Taylor Swift",
      description: "Nghệ sĩ",
      newtype: 1,
    },
    {
      image: require("../assets/album/Rectangle 189 (36).png"),
      title: "Rhymastic",
      description: "Nghệ sĩ",
      newtype: 1,
    },
    {
      image: require("../assets/album/Rectangle 189 (37).png"),
      title: "B Ray",
      description: "Nghệ sĩ",
      newtype: 1,
    },
    {
      image: require("../assets/album/Rectangle 189 (38).png"),
      title: "Rich Choi",
      description: "Nghệ sĩ",
      newtype: 1,
    },
    {
      image: require("../assets/album/Rectangle 189 (39).png"),
      title: "Low G",
      description: "Nghệ sĩ",
      newtype: 1,
    },
  ],
  title: "Theo dõi",
  description: "",
  category_title: "",
  category_count: "",
  category_content: ``,
  type: 0,
};
export const new_music_data = [
  {
    image: require("../assets/images/Rectangle 225.png"),
    title: "Tình Đắng Như Ly Cà Phê",
    artist: "Ngơ",
    newtype: 0,
    url: require("../assets/music/Tinh Dang Nhu Ly Ca Phe - Ngo ft Nan (1).m4a"),
    duration: "3:36",
    currentTime: 0,
  },
  {
    image: require("../assets/images/Rectangle 225 (1).png"),
    title: "Metronome",
    artist: "Kenshi Yonezu",
    newtype: 0,
    url: require("../assets/music/Metronome - Jay Park_ Simon Dominic_ Gra.m4a"),
    duration: "3:59",
    currentTime: 0,
  },
  {
    image: require("../assets/images/Rectangle 225 (2).png"),
    title: "Feeling Are Faltal",
    artist: "mxmtool",
    duration: "4:47",
    newtype: 0,
    url: require("../assets/music/Tinh Dang Nhu Ly Ca Phe - Ngo ft Nan (1).m4a"),
    duration: "3:36",
    currentTime: 0,
  },
  {
    image: require("../assets/images/Rectangle 225 (3).png"),
    title: "Hold",
    artist: "Ngơ",
    duration: "3:45",
    newtype: 0,
    url: require("../assets/music/Tinh Dang Nhu Ly Ca Phe - Ngo ft Nan (1).m4a"),
    duration: "3:36",
    currentTime: 0,
  },
  {
    image: require("../assets/images/Rectangle 225 (4).png"),
    title: "Colors",
    artist: "Ngơ",
    duration: "3:45",
    newtype: 0,
    url: require("../assets/music/Tinh Dang Nhu Ly Ca Phe - Ngo ft Nan (1).m4a"),
    duration: "3:36",
    currentTime: 0,
  },
];

export const playlist_data = {
  playlist_data_1: {
    banner_img: require("../assets/images/Rectangle 238.png"),
    artist_img: require("../assets/images/Rectangle 217.png"),
    artist_small_img: require("../assets/images/Ellipse 29.png"),
    title: "PLAYLIST 1",
    artist: "En",
    song_count: 18,
    time: 44,
    list_data: [
      {
        image: require("../assets/images/Rectangle 225.png"),
        title: "Tình Đắng Như Ly Cà Phê",
        artist: "Ngơ",
        duration: "3:45",
        date_add: "27/12/2022",
        description: "Ngơ",
        currentTime: 0,
        url: require("../assets/music/Born To Die - Lana Del Rey.m4a"),
        newtype: 0,
      },
      {
        image: require("../assets/images/Rectangle 225 (1).png"),
        title: "Metronome",
        artist: "Kenshi Yonezu",
        duration: "4:45",
        date_add: "26/12/2022",
        description: "Metronome",
        currentTime: 0,
        url: require("../assets/music/Born To Die - Lana Del Rey.m4a"),
        newtype: 0,
      },
      {
        image: require("../assets/images/Rectangle 225 (2).png"),
        title: "Feeling Are Faltal",
        artist: "mxmtool",
        duration: "4:47",
        date_add: "26/12/2022",
        description: "Ngơ",
        currentTime: 0,
        url: require("../assets/music/Born To Die - Lana Del Rey.m4a"),
        newtype: 0,
      },
      {
        image: require("../assets/images/Rectangle 225 (3).png"),
        title: "Hold",
        artist: "Ngơ",
        duration: "3:45",
        date_add: "25/12/2022",
        description: "Ngơ",
        currentTime: 0,
        url: require("../assets/music/Born To Die - Lana Del Rey.m4a"),
        newtype: 0,
      },
      {
        image: require("../assets/images/Rectangle 225 (4).png"),
        title: "Colors",
        artist: "Ngơ",
        duration: "3:45",
        date_add: "25/12/2022",
        description: "Ngơ",
        currentTime: 0,
        url: require("../assets/music/Born To Die - Lana Del Rey.m4a"),
        newtype: 0,
      },
    ],
  },
  playlist_data_2: {
    banner_img: require("../assets/images/Rectangle 238.png"),
    artist_img: require("../assets/images/Rectangle 246 (1).png"),
    artist_small_img: require("../assets/images/Rectangle 189 (40).png"),
    title: "PLAYLIST 2",
    artist: "En",
    song_count: 18,
    time: 44,
    list_data: [
      {
        image: require("../assets/home/Rectangle 189 (8).png"),
        title: "New Light",
        artist: "Eric Bellinger",
        duration: "2:33",
        description: "Ngơ",
        currentTime: 0,
        url: require("../assets/music/Born To Die - Lana Del Rey.m4a"),
        newtype: 0,
      },
      {
        image: require("../assets/home/Rectangle 189 (9).png"),
        title: "Ziggly Mixtapes",
        artist: "Haziq Hafiy",
        duration: "3:09",
        description: "Ngơ",
        currentTime: 0,
        url: require("../assets/music/Born To Die - Lana Del Rey.m4a"),
        newtype: 0,
      },
      {
        image: require("../assets/home/Rectangle 189 (10).png"),
        title: "Take a trip",
        artist: "Postwood",
        duration: "1:03",
        description: "Ngơ",
        currentTime: 0,
        url: require("../assets/music/Born To Die - Lana Del Rey.m4a"),
        newtype: 0,
      },
      {
        image: require("../assets/home/Rectangle 189 (11).png"),
        title: "Happier Than Ever",
        artist: "Billie Eilish",
        duration: "5:08",
        description: "Ngơ",
        currentTime: 0,
        url: require("../assets/music/Born To Die - Lana Del Rey.m4a"),
        newtype: 0,
      },
      {
        image: require("../assets/home/Rectangle 189 (12).png"),
        title: "Say So",
        artist: "Nicki Minaj",
        duration: "8:09",
        description: "Ngơ",
        currentTime: 0,
        url: require("../assets/music/Born To Die - Lana Del Rey.m4a"),
        newtype: 0,
      },
      {
        image: require("../assets/home/Rectangle 189 (13).png"),
        title: "Cure For Me",
        artist: "AURORA",
        duration: "7:03",
        description: "Ngơ",
        currentTime: 0,
        url: require("../assets/music/Born To Die - Lana Del Rey.m4a"),
        newtype: 0,
      },
      {
        image: require("../assets/home/Rectangle 189 (14).png"),
        title: "Bohemian Rhap...",
        artist: "Queen",
        duration: "1:50",
        description: "Ngơ",
        currentTime: 0,
        url: require("../assets/music/Born To Die - Lana Del Rey.m4a"),
        newtype: 0,
      },
    ],
  },
};
